package cn.sysu.spring.entity;

public class Big {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big.id
     *
     * @mbg.generated Sun May 12 18:40:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column big.number
     *
     * @mbg.generated Sun May 12 18:40:42 CST 2019
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big.id
     *
     * @return the value of big.id
     *
     * @mbg.generated Sun May 12 18:40:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big.id
     *
     * @param id the value for big.id
     *
     * @mbg.generated Sun May 12 18:40:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column big.number
     *
     * @return the value of big.number
     *
     * @mbg.generated Sun May 12 18:40:42 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column big.number
     *
     * @param number the value for big.number
     *
     * @mbg.generated Sun May 12 18:40:42 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}