package cn.sysu.spring.mapper;

import cn.sysu.spring.entity.Big;
import cn.sysu.spring.entity.BigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big
     *
     * @mbg.generated Sun May 12 18:40:42 CST 2019
     */
    long countByExample(BigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big
     *
     * @mbg.generated Sun May 12 18:40:42 CST 2019
     */
    int deleteByExample(BigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big
     *
     * @mbg.generated Sun May 12 18:40:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big
     *
     * @mbg.generated Sun May 12 18:40:42 CST 2019
     */
    int insert(Big record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big
     *
     * @mbg.generated Sun May 12 18:40:42 CST 2019
     */
    int insertSelective(Big record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big
     *
     * @mbg.generated Sun May 12 18:40:42 CST 2019
     */
    List<Big> selectByExample(BigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big
     *
     * @mbg.generated Sun May 12 18:40:42 CST 2019
     */
    Big selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big
     *
     * @mbg.generated Sun May 12 18:40:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") Big record, @Param("example") BigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big
     *
     * @mbg.generated Sun May 12 18:40:42 CST 2019
     */
    int updateByExample(@Param("record") Big record, @Param("example") BigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big
     *
     * @mbg.generated Sun May 12 18:40:42 CST 2019
     */
    int updateByPrimaryKeySelective(Big record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big
     *
     * @mbg.generated Sun May 12 18:40:42 CST 2019
     */
    int updateByPrimaryKey(Big record);
}